### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by Rohit-554** [Rohit-554/Notes_App#1]
Type of the parameter must be a class annotated with @Entity or a collection/array of it.
 kotlin.coroutines.Continuation<? super kotlin.Unit> continuation);

If you can solve that, It will be grateful, just give your comment...

**Comment by netchild76** [comment]
Hi, 
you need to update the ROOM version from 2.3.0 (that you are using) to 2.4.2

How? 
go to ext section in build.gradle project and modify roomVersion to 2.4.2 

ext {

    roomVersion = '2.4.2'
}

**Comment by Rohit-554** [comment]
Thanks , but now i am getting more erros like..

androidx.appcompat.widget.AppCompatImageView cannot be cast to android.widget.Button
        at com.example.notes_app.NotesRVadapter$NoteViewHolder.<init>(NotesRVadapter.kt:21)
        at com.example.notes_app.NotesRVadapter.onCreateViewHolder(NotesRVadapter.kt:26)
        at com.example.notes_app.NotesRVadapter.onCreateViewHolder(NotesRVadapter.kt:15)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235).....

do you know how to solve?

**Comment by Rohit-554** [comment]
Thanks , but now i am getting more erros like..

androidx.appcompat.widget.AppCompatImageView cannot be cast to android.widget.Button
        at com.example.notes_app.NotesRVadapter$NoteViewHolder.<init>(NotesRVadapter.kt:21)
        at com.example.notes_app.NotesRVadapter.onCreateViewHolder(NotesRVadapter.kt:26)
        at com.example.notes_app.NotesRVadapter.onCreateViewHolder(NotesRVadapter.kt:15)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235).....

**Comment by Rohit-554** [comment]
Thanks Dude I got my solution, 
Updating room worked ....
and actually i was using image view instead of button that's why i am getting lot many errors , I resolved replaced imageview with Button it worked .. Yooo

**Comment by Rohit-554** [comment]
> Hi, you need to update the ROOM version from 2.3.0 (that you are using) to 2.4.2
> 
> How? go to ext section in build.gradle project and modify roomVersion to 2.4.2
> 
> ext {
> 
> ```
> roomVersion = '2.4.2'
> ```
> 
> }
